# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170118_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='escala',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=128),
        ),
    ]
