# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170125_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
    ]
