# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170518_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='personas',
            field=models.ManyToManyField(through='core.Registro', to='core.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='preguntas',
            field=models.ManyToManyField(through='core.Registro', to='core.Pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='personas',
            field=models.ManyToManyField(through='core.Registro', to='core.Persona'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.Persona'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.Periodo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.Pregunta'),
        ),
    ]
