# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170523_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='codigo',
            new_name='persona',
        ),
        migrations.AlterUniqueTogether(
            name='registro',
            unique_together=set([('pregunta', 'persona', 'periodo')]),
        ),
    ]
