# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170523_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.CharField(max_length=256),
        ),
    ]
