# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170524_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
